### ISSUE TITLE
conflict with Batterynotch

### ISSUE THREAD

**Issue by League2EB** [brendonjkding/NoPassAfterRespring#2]
## Thank you

 for your hard work for such a nice Tweak

But I found a conflict with [Batterynotch](https://repo.packix.com/package/com.gilshahar7.batterynotch/), 

can you try to solve it?

Thank you so much

**Comment by brendonjkding** [comment]
This Tweak works by turning on the hidden option dontLockAfterCrash. Then the SpringBoard itself doesn’t show lockscreen. 

What I mean is that it can't be fixed on my side.

**Comment by League2EB** [comment]
Okay, I'm trying to give back to Batterynotch
thx all
